#!/usr/bin/env bash

for file in `find . -type f -name "*.parenscript"`; do
    jsfile=${file/parenscript/js}
    if [ -f "$jsfile" ]; then
        rm --verbose "$jsfile"
    fi
done

for file in `find . -type f -name "*.fasl"`; do
    rm --verbose $file
done